language: node_js
node_js:
  - "14"

branches:
  only:
    - main

script:
  - npm run test

env:
  global:
    - ACCESS_TOKEN_SECRET=ireporter-access-token-secret

deploy:
  provider: heroku
  api_key: 5e4a10e2-0e59-4cf7-9e12-a9e32609990f
  app: ireporter-be
